### ISSUE TITLE
Investigate UI improvements for picking stitch colors.

### ISSUE THREAD

**Issue by connorlay** [KnitGrid/knitgrid-android#20]
Selecting stitch colors takes too many clicks! We need to investigate alternative UI options for allowing users to set stitch color during pattern creation.

Acceptance criteria:
- A suitable UI option has been decided upon that reduces number of clicks to set a stitch color.
- A visual representation of this UI flow is created.

**Comment by Magisus** [comment]
So one major flow change I want to make is that however a color is selected, all future stitches placed will be of that color until the user changes the color again. Also, when the user selects a color, the stitch button backgrounds will change to that color, as a clear visual of the current color selection. Our color picker also needs to actually show what the colors look like, instead of just using words.

For this flow, it no longer makes sense for color selection to be triggered by long-clicking on a stitch. Rather, I think it should somehow be integrated into the button bar.  One idea is a little button that does something like causes a drawer to slide open above the stitch buttons and displays color options as squares of color. (If we eventually decide to support arbitrary color instead of just presets, this could be modified to display a spectrum or even full color wheel.) Once the user selects a color, the drawer closes and all buttons' backgrounds change to reflect the choice.

**Comment by Magisus** [comment]
![color-tab-mockup](https://cloud.githubusercontent.com/assets/839145/15687567/4aecfd00-272a-11e6-9fa9-079181074c0e.png)


The shadowing didn't come out right in the screen shot, but my idea would be to use it to make the bars appeared layered, i.e. the color bar slides out from underneath the stitch bar when the tab is clicked. Icon and colors up for debate, but this is a place to start.

**Comment by connorlay** [comment]
> So one major flow change I want to make is that however a color is selected, all future stitches placed will be of that color until the user changes the color again.

I agree. That should help speed up the process of creating a pattern.

> One idea is a little button that does something like causes a drawer to slide open above the stitch buttons and displays color options as squares of color.

That sounds like a good idea. Another option is we could put the long click event on the stitch buttons themselves, rather than introducing another button into the bar. That's a common pattern when altering the form of what's represented on the button itself (like adding accents to letters on the keyboard). Either way I think this is a good direction to move in 😄

**Comment by Magisus** [comment]
Oh really? I guess I hadn't seen that very much before, except maybe with keyboards. But even then it doesn't tend to alter state permanently, just for one click. It would certainly be easier to implement, but I worry that it falls too much into hidden functionality. But maybe that's not an issue. We could always provide a walkthrough on first use or something. Maybe I'll start with that, since it's an easy UI feature to implement, and see how it feels. If we don't like it we can go to something more complicated.

**Comment by connorlay** [comment]
> But even then it doesn't tend to alter state permanently, just for one click.

That's a good point. I guess that would be kinda weird.

> We could always provide a walkthrough on first use or something.

We should try to avoid having to explain basic things like this. Idk I'm not a UX designer so what do I know 😛

**Comment by Magisus** [comment]
I think I want to try it and see what it feels like. If the long click still seems annoying we can investigate alternatives. Cause part of the problem I have with the current system is the delay, but if it's less frequent it might be okay.
